export const ActionTypes = {

  // Trade Execution Actions
  START_TRADE_EXECUTION: 'START_TRADE_EXECUTION',
  EXECUTE_TRADE: 'EXECUTE_TRADE',
  ASSESS_RISK: 'ASSESS_RISK',
  PLACE_TRADE: 'PLACE_TRADE',
  CANCEL_TRADE: 'CANCEL_TRADE',
  MODIFY_TRADE: 'MODIFY_TRADE',
  GET_TRADE_STATUS: 'GET_TRADE_STATUS',

  // Portfolio Management Actions
  VIEW_PORTFOLIO: 'VIEW_PORTFOLIO',
  UPDATE_PORTFOLIO: 'UPDATE_PORTFOLIO',
  GET_PERFORMANCE: 'GET_PERFORMANCE',
  GET_PORTFOLIO: 'GET_PORTFOLIO',
  GET_POSITIONS: 'GET_POSITIONS',
  GET_ORDERS: 'GET_ORDERS',
  GET_ACCOUNT: 'GET_ACCOUNT',
  GET_RISK_METRICS: 'GET_RISK_METRICS',
  GET_ALERTS: 'GET_ALERTS',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  CLEAR_ALERTS: 'CLEAR_ALERTS',

  // Risk Management Actions
  CALCULATE_POSITION_SIZE: 'CALCULATE_POSITION_SIZE',
  SET_STOP_LOSS: 'SET_STOP_LOSS',
  SET_TAKE_PROFIT: 'SET_TAKE_PROFIT',
} as const; 